{% set version = "3.3.6" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: 97618b3699fad3f1957111c3e6f3f929cf6a07073eabbc40e4513a53d844bce5

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - numpy
    - matplotlib-base
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: FloPy is a Python package for developing, running, and post-processing MODFLOW-based models

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
