{% set version = "3.2.11" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: 9af5d7779667240c1157e3e441862ef75ada046fe294fc0afcb52e0f695f86e5

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
    - numpy
    - matplotlib
    - enum34  # [py27]
  run:
    - python
    - numpy
    - matplotlib
    - enum34  # [py27]

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'FloPy is a Python package for developing, running, and post-processing MODFLOW-based models'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
