{% set name = "flopy" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flopy-{{ version }}.tar.gz
  sha256: d0f0cca3cfed3959c16d923cbd38aefc6fa4304f732f5cb56dce33a401f467ce

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - pandas >=2.0.0
    - python >=3.8
    - numpy >=1.15.0,<2.0.0
    - matplotlib-base >=1.4.0

test:
  imports:
    - flopy
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip

about:
  home: https://github.com/modflowpy/flopy
  summary: FloPy is a Python package to create, run, and post-process MODFLOW-based models
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
