{% set version = "3.3.1" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: b7e701b0aea0409139238bc931f2767e40e7ab55762c2e01a512f8405c801580

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - numpy
    - matplotlib-base
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: FloPy is a Python package for developing, running, and post-processing MODFLOW-based models

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
