{% set version = "3.3.0" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: a354695630b8104421aa94c48ee87b744ca6f4a58697f1972b904090f1ce770f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
    - numpy
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'FloPy is a Python package for developing, running, and post-processing MODFLOW-based models'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
