{% set version = "3.2.13" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: 1724b5b22214f12888952a44d8db64701c8099386d8821f3e8c8de376fcb11ed

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
    - numpy
    - matplotlib
    - enum34  # [py27]
  run:
    - python
    - numpy
    - matplotlib
    - enum34  # [py27]

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'FloPy is a Python package for developing, running, and post-processing MODFLOW-based models'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
