{% set version = "3.2.7" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: 02737892c9598514ce7684a9ef9d47d2c66ad04a24d306dac7af5be537b51836

build:
  number: 0
  script: 
    - if [[ $CONDA_PY == 2.7 ]]; then conda install enum34; fi    
    - python setup.py install --single-version-externally-managed  --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - enum34  # [py27]
  run:
    - python
    - numpy
    - matplotlib
    - enum34  # [py27]

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD 3-Clause
  summary: 'FloPy is a Python package for developing, running, and post-processing MODFLOW-based models.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
