{% set version = "3.4.0" %}

package:
  name: flopy
  version: {{ version }}

source:
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: c63c4f1c39f66da4820abb33c97d218387e8906a45e4a8610ad3673338e0ef29

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >45
  run:
    - python >=3.7
    - numpy >=1.15.0
    - matplotlib-base >=1.4.0

test:
  imports:
    - flopy
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip

about:
  home: https://github.com/modflowpy/flopy
  license: CC0-1.0
  license_file: LICENSE.md
  summary: FloPy is a Python package for developing, running, and post-processing MODFLOW-based models

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
