schema_version: 1

context:
  name: flopy
  version: "3.11.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/flopy-${{ version }}.tar.gz
  sha256: b68006f33956b2c86f263084fddf3e5d39b7e57021a600b48350c5ebafe1fac8

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - get-modflow = flopy.utils.get_modflow:cli_main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.20.3,<3.0
    - matplotlib-base >=1.4.0
    - pandas >=2.0.0
  extras:
    codegen:
      - boltons >=1.0
      - Jinja2 >=3.0
      - modflow-devtools >=1.7.0,!=1.9.0,<2
      - tomli
      - tomli-w

    optional:
      - affine
      - descartes
      - fiona
      - geojson
      - geopandas
      - GitPython
      - h5py
      - imageio
      - netcdf4
      - pooch
      - pymetis
      - pyproj
      - pyshp
      - pyvista
      - rasterio
      - rasterstats
      - scikit-learn
      - scipy
      - shapely >=2.0
      - vtk >=9.4.0
      - xmipy

tests:
  - python:
      imports:
        - flopy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - get-modflow --help

about:
  summary: FloPy is a Python package to create, run, and post-process MODFLOW-based models
  license: CC0-1.0
  license_file: LICENSE.md
  homepage: https://github.com/modflowpy/flopy

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-dev
    - mwtoews
