appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XM4B4dlI0i8qE1fmXpJK/VxNwfD7s1mQFovHe6vNGakvRWg7XCGRfhZg3neEmTVS5Xh6RblnDAxhJk/Q3+lfoDoDe5b8z7yWk4f4Hk/A8RX9/SL8treM5mLQ+lhWqZkYVn4+ICAhuYv8WaDHCYjpte2tNYAh7v+0CvjjQU6YFqYwMB8yTqt+gUMIVIEnnYHVF0+aPXi0WpWflVkku//8xCIdxLpshjtOGsIWVkP2bgFsNvbQkcf6abTEjoFMwphHShPZ25WYv5el6B/DZjKzFJksNimPtmsHD1fRwXduHZzMFDh5lH80tyugPFc6ITZwbWdWQ+F4KokC4eYHAoN1iV/snNk3mnnnHuA77VbZ19SJmwUJ0rE332CB1vRy95sWgdYQO8J3Hdqwqi9FEuPgOFxvT6Y6LkzwndBuVc51OMrd9M3RIzwK5vFZAHt/V/vR2D745kv8NQ3WzgA3PnZ1ZAGamzDsFV+1tMATEQ2eDFhYpImiWETHeGxfqvjax/8CZXE0yqz5EKblGor7WZI2o5HD5qCS8GwUwljZBLiZRSfFpkuAHcsDUDkucYaJsI8U/jzmrYT7h8p2vxlpQ9iokT3mbXcWRKpptvnXKI77JjK82dD/oPKKkgBafIIOUiMkdm2mOGk447sYmVS01zsi0zO+peYNklqSzvTQKvuLby4=}
